apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-chart.fullname" . }}-config
  labels:
    {{- include "nginx-chart.labels" . | nindent 4 }}
data:
  nginx.conf: |
{{ .Values.nginx.config | indent 4 }}
